### ISSUE TITLE
Audio guide?

### ISSUE THREAD

**Issue by viktorstrate** [cmer/gigabyte-z390-aorus-master-hackintosh#12]
Thank you so much for sharing this repo.

In the readme, you explain that on-board audio is working.
I see that you set inject to `16` under `Devices`, but that alone doesn't seem to work for me.

Can you explain what you did to get it working, or refer me to the resource you used?

**Comment by w1013d27** [comment]
In Boot, add an argument alcid=7. It does work for me!

**Comment by phuonghoanglua** [comment]
> =

no luck with me. still no sound.

**Comment by phuonghoanglua** [comment]
> In Boot, add an argument alcid=7. It does work for me!

no luck with me. still no sound

**Comment by viktorstrate** [comment]
I was able to get it working on my system.
I however, have a `Gigabyte z390 aorus pro mini-ITX` motherboard.

I updated to the latest relase version of [AudioALC](https://github.com/acidanthera/AppleALC/releases) (1.3.6).
I set inject to `16` under `Devices`, like explained in the guide, and made sure to enable `ResetHDA` next to it.

@w1013d27 + @phuonghoanglua, adding `aclid=7` didn't work for me either.

You can download my config.plist here, if you wan't to have a closer look:
[config.plist](https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/files/2997111/config.plist.zip)

**Comment by MyGHz** [comment]
Great guide mate, thanks. But I to am having issues with no sound,  I have tried the above but to no avail. I have the same motherboard with the i7 8700k. Any help would be truly appreciated. 
Thank you kindly.

**Comment by l35l33** [comment]
hi, i wanna thank cmer for the easy hackintosh build and share my experience regarding audio problem in catalina
my system is :
i9 9900k
z390 aorus master
msi rx 5700 xt gaming x
fenvi t919
500gb ssd 860 evo 
corsair 4x8gb vengeance rgb 3200mhz

i clean installed catalina with new ssd following your guide on building my config.plist and generating SN in SMBIOS via clover exactly as cmer described. it works wonderfully. 
regarding the discussion of catalina audio, i, too, experience problem with the audio similar to the topic. here's what happened 
1. after following cmer's guide, audio works right away using layout-id=16 without inject and resetHDA in Devices
2. then i put in 2nd ssd and installing win 10x64, this is when the trouble 
3. i installed z390 wifi with Intel pro wireless wifi downloaded from gigabyte's website and suddenly layout-id=16 no longer works
4. i removed layout-id=16 and use inject 5 or 7 (1, 2, 3 not working, havent tried 11) and checked ResetHDA
5. i returned to win10 and installed Realtek HD Audio also downloaded from gigabyte's website, then inject 5 or 7 will stop working
6. at this point, neither layout-id=16 nor inject method works
7. then i uninstall intel wifi driver and Realtek HDA driver and both method works again
the problem was intel wifi driver cannot be uninstalled from control panel - apps. it has to be removed from device manager with the box "delete device software" checked to ensure windows doesnt automatically install them when you "scan for hardware changes".
8. i already checked other drivers and doubled out the two drivers above. it seems installing (or uninstalling) chipsets, INFupdate, LAN, Intel graphic, raid drivers doesnt affect audio in catalina.

i'm not a programmer so i dont have any idea how big changes win drivers can do to mac system in other hdd. i suspect both the drivers changes bios setting somehow. maybe there are people here interested in finding "a permanent cure", that would be awesome.
as of right now, i dont install realtek HD audio, and using built iin win10x64 drivers for sound. as for wifi and bluetooth, i didn't install it either, i already have fenvi t919 pci card, so i'm using it instead of z390 onboard wifi.

there's another guide by audiogod that involves upgrading the bios to fw10 (i'm still at fw8) that i havent tried yet. maybe with updated bios and custom DSDT inject the problem would not happenned, i dont know...

once again, many thanks for cmer's guide, you rock dude!
