### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by MyGHz** [cmer/gigabyte-z390-aorus-master-hackintosh#22]
Great guide mate, thanks. But I to am having issues with no sound, I have tried the mentioned solutions in the "audio guide?" issue raised, but to no avail. I have the same motherboard (z390 master) with the i7 8700k. Any help would be truly appreciated.
Thank you kindly.

**Comment by cmer** [comment]
Is the audio device recognized? did you follow the instructions to enable audio? does it work with my `config.plist`?

**Comment by korzhyk** [comment]
@MyGHz due mistakes in @cmer config.plist, try using official instructions to get working Audio https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage

**Comment by cmer** [comment]
@korzhyk what are the mistakes in my plist? Last I used onboard audio it was working just fine. I want to make sure I update my config file if there's indeed mistakes.

**Comment by korzhyk** [comment]
@cmer `layout-id` https://github.com/cmer/gigabyte-z390-aorus-master-hackintosh/blob/master/MY%20EFI/CLOVER/config.plist#L113 must be injected through DSDT or properties injection or `boot-args`.

**Comment by cmer** [comment]
@korzhyk it was working perfectly fine as is for me. Has anything changed in the recent months?

**Comment by korzhyk** [comment]
@cmer set `layout-id` by Clover is deprecated since `AppleALC.kext` is released.

**Comment by cmer** [comment]
Can you point me to documentation saying so? I think you're mistaken. For example, [this guide](https://www.reddit.com/r/hackintosh/comments/4e23w6/guide_native_audio_with_clover_applealckext/) injects `layout-id` exactly the same way I did.

**Comment by manHands** [comment]
I think what @korzhyk is referring to is what is stated in the wiki referenced above...

> Note: It is necessary to set value `layout-id` in `Devices-Properties` or boot arguments. HDEF device locations `PciRoot`, gfxutil may be used: `gfxutil -f HDEF`

So rather than using `Audio-Inject`, we should be using the `PciRoot` location with the correct `layout-id` for this board.

	<key>Devices</key>
	<dict>
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
			<dict>
				<key>layout-id</key>
				<data>EAAAAA==</data>
			</dict>
		</dict>
	</dict>

**Comment by MyGHz** [comment]
Hi, thanks for the replies and help, but i tried to install Mojave again today, it seems to be working fine as I am typing this, didn't do anything different, but I am happy so thanks again for the help.

**Comment by cmer** [comment]
@MyGHz so you are confirming that my EFI works fine as-is for audio? Just want to make sure we document this for future users. thanks!

**Comment by amitra1997** [comment]
FIX:

Update AppleALC.kext
Remove "change HDAS to HDEF" from acpi patches
Add "alcid=16" to the boot arguments for layout-id injection
Set Inject to "No" under Audio section
Reboot and success!

**Comment by l35l33** [comment]
hi, i wanna thank cmer for the easy hackintosh build and share my experience regarding audio problem in catalina
my system is :
i9 9900k
z390 aorus master
msi rx 5700 xt gaming x
fenvi t919
500gb ssd 860 evo 
corsair 4x8gb vengeance rgb 3200mhz

i clean installed catalina with new ssd following your guide on building my config.plist and generating SN in SMBIOS via clover exactly as cmer described. it works wonderfully. 
regarding the discussion of catalina audio, i, too, experience problem with the audio similar to the topic. here's what happened 
1. after following cmer's guide, audio works right away using layout-id=16 without inject and resetHDA in Devices
2. then i put in 2nd ssd and installing win 10x64, this is when the trouble 
3. i installed z390 wifi with Intel pro wireless wifi downloaded from gigabyte's website and suddenly layout-id=16 no longer works
4. i removed layout-id=16 and use inject 5 or 7 (1, 2, 3 not working, havent tried 11) and checked ResetHDA
5. i returned to win10 and installed Realtek HD Audio also downloaded from gigabyte's website, then inject 5 or 7 will stop working
6. at this point, neither layout-id=16 nor inject method works
7. then i uninstall intel wifi driver and Realtek HDA driver and both method works again
the problem was intel wifi driver cannot be uninstalled from control panel - apps. it has to be removed from device manager with the box "delete device software" checked to ensure windows doesnt automatically install them when you "scan for hardware changes".
8. i already checked other drivers and doubled out the two drivers above. it seems installing (or uninstalling) chipsets, INFupdate, LAN, Intel graphic, raid drivers doesnt affect audio in catalina.

i'm not a programmer so i dont have any idea how big changes win drivers can do to mac system in other hdd. i suspect both the drivers changes bios setting somehow. maybe there are people here interested in finding "a permanent cure", that would be awesome.
as of right now, i dont install realtek HD audio, and using built iin win10x64 drivers for sound. as for wifi and bluetooth, i didn't install it either, i already have fenvi t919 pci card, so i'm using it instead of z390 onboard wifi.

there's another guide by audiogod that involves upgrading the bios to fw10 (i'm still at fw8) that i havent tried yet. maybe with updated bios and custom DSDT inject the problem would not happenned, i dont know...

once again, many thanks for cmer's guide, you rock dude!

**Comment by l35l33** [comment]
@amitra1997 doesnt work for dual boot. in single os system, yes, no problem. i can confirm this.

**Comment by thadjbullet** [comment]
I have same issue. For now I solved it by change win to Mac through power off instead reboot. It’s because windows set volume level to 0 and Mac cannot set it back. Working on fix

**Comment by l35l33** [comment]
@thadjbullet it doesnt seem so. layout 7 and 16 have 5 outputs which is similar
digital (greyed out on mine)
internal (on 16) / headphones (on 7)
line out
line out
monitor 
only internal and headphones are affected by the win10 driver. i have a sub connected to line out that is still outputing sounds and my monitor also still can be used normally

**Comment by thadjbullet** [comment]
You right. That’s how it works. Just try to change OS by power off

**Comment by l35l33** [comment]
@thadjbullet so you're saying windows only set the volume level of one output? maybe the output of current device we select when we reboot. have you tried changing the output in windows to other device, such as digital or monitor, before rebooting, to see whether only that particular device is set to 0 ?

**Comment by thadjbullet** [comment]
I don't try it.
U can read more here [https://github.com/Dolnor/EAPD-Codec-Commander/issues/9](url)
