### ISSUE TITLE
Enable IGPU HDMI output

### ISSUE THREAD

**Issue by tomleavy** [cmer/gigabyte-z390-aorus-master-hackintosh#31]
Take a look at the link below, Aorus master is listed there and I have tested it out, works no problem. This is really useful because I'm dual booting with Windows and my GPU is a GTX 2070 so I am forced to use only intel graphics on the Hackintosh side. I actually just have both the HDMI from the MB and the display port from my Nvidia card plugged into the same monitor and it seems to work seamlessly. 

https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/

**Comment by cmer** [comment]
This is not something I'll add to my guide because it's impossible for me to boot with iGPU enabled because I have too many PCIe devices (unless I use the free2000-patched mem fix). 

Also, my objective is to have a system that is as close as possible to an `iMacPro1,1`, which doesn't use an iGPU.

Glad you found a way to make it work for you, though!
