### ISSUE TITLE
Various (HDMI connect and intel RST raid on Boot)

### ISSUE THREAD

**Issue by rmackenney** [cmer/gigabyte-z390-aorus-master-hackintosh#37]
Hi,
First of all, I appreciate your collaboration.

I have a Gigabyte aorus master MOBO with i9-9900k processor and ASUS ROG-STRIX-RXVEGA64-O8G-GAMING as Video.
The first question is:
When you start with FlashDrive, where do you have the HDMI monitor connected, on the iGFX or on the external video card?
I ask because if I connect in iGFX, the starting is very slow, the bar almost does not advance, and if I connect externally, I get to a small screen that shows nothing. (I changed the "DVMT Pre-Allocated" parameter to 32M).
Please any recommendations?
The second question is:
In the same MOBO, I have 2 SSDs PCIe in Raid 0 (with Intel RST), but the MacOS installer doesn't recognize it. Do you know any way for MacOS to work with that Hardware?

**Comment by cmer** [comment]
Not sure if MacOS would recognize Intel RST raid. I doubt it.
You can't use the iGPU for your display, since a real imac19,1 doesn't actually use the iGPU for displays. There might be a way to make it work, but this is not something I've attempted since I always try to stay close to the real thing to avoid issues.

**Comment by rmackenney** [comment]
sorry for so long… Thank you!!!
