### ISSUE TITLE
iGPU

### ISSUE THREAD

**Issue by sebikolo** [cmer/gigabyte-z390-aorus-master-hackintosh#57]
Were you able to launch iGPU? When I have iGPU enabled in bios I have an error:

ERROR allocating 0x1199b pages at 0x000000007842000 alloc type 2
Couldn't allocate runtime area
Boot failed; will sleep for 10 seconds before exiting...

My configuration:
- Z390 Aorus Master
- i9-9900k
- 64GB RAM
- Samsung SSD 970 EVO 500GB
- RX 5700 XT

**Comment by ToxicLand** [comment]
I've been able to fix this using this guide: https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/extras/kalsr-fix

**Comment by yyjazsf** [comment]
@sebikolo  would you tell me  What brand of your  RX5700 XT？I bought one,usually Black screen

**Comment by thadjbullet** [comment]
@yyjazsf It requires WhateverGreen, Lilu and agdpmod=pikera/ignore boot argument.

**Comment by sebikolo** [comment]
> @sebikolo would you tell me What brand of your RX5700 XT？I bought one,usually Black screen

SAPPHIRE NITRO+ RADEON RX 5700 XT

**Comment by yyjazsf** [comment]
> @yyjazsf It requires WhateverGreen, Lilu and agdpmod=pikera/ignore boot argument.

thanks all，I use `WhateverGreen, Lilu and agdpmod=pikera`.

@sebikolo  I bought card was `SAPPHIRE  RX 5700XT 8G OC`, 
Many people buy graphics cards with this problem（both windows and hackintosh）

**Comment by quiggy** [comment]
I have a working version For Catalina with disabled dedicated gpu. I am using igpu instead. This is helpfull For People with nvidia cards who want to Use Catalina. are you interested in a pr documenting the nessecary changes? It might help People searching For a Solution. For me it took some time to find the right settings

**Comment by chengrutw** [comment]
@quiggy , could you please share? I'm interested in knowing more. Thanks!

**Comment by quiggy** [comment]
I used the config and files in this repo as the basis for my efi. Then made the following changes to support the internal gpu:

1. Modify the boot arguments in config.plist to the following: 

keepsyms=1 
dart=0
debug=0x100
alcid=16 (enable Audio)
slide=0
-wegnoegpu (disable dGPU)

2. In Clover Config ACPI you have to add the Patch Change GFX0 to IGPU again.

3. You have to add the following patch to Clover Config - Devices - Properties:

<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x1f,0x3)</key>
			<dict>
				<key>AAPL,slot-name</key>
				<string>Internal@0,31,3</string>
				<key>device_type</key>
				<string>Audio device</string>
				<key>hda-gfx</key>
				<string>onboard-2</string>
				<key>layout-id</key>
				<data>AAAAAA==</data>
				<key>model</key>
				<string>Cannon Lake PCH cAVS</string>
			</dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>AAPL,GfxYTile</key>
				<data>AQAAAA==</data>
				<key>AAPL,ig-platform-id</key>
				<data>BwCbPg==</data>
				<key>AAPL,slot-name</key>
				<string>Internal@0,2,0</string>
				<key>device-id</key>
				<data>mz4AAA==</data>
				<key>device_type</key>
				<string>VGA compatible controller</string>
				<key>enable-hdmi-dividers-fix</key>
				<data>AQAAAA==</data>
				<key>enable-hdmi20</key>
				<data>AQAAAA==</data>
				<key>framebuffer-con0-alldata</key>
				<data>AgISAAAIAACHAQAAAwQSAAAIAACHAQAAAQESAAAIAACHAQAA</data>
				<key>framebuffer-con0-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-fbmem</key>
				<data>AAAAAA==</data>
				<key>framebuffer-patch-enable</key>
				<data>AQAAAA==</data>
				<key>framebuffer-stolenmem</key>
				<data>AACQAw==</data>
				<key>framebuffer-unifiedmem</key>
				<data>AAAAgA==</data>
				<key>hda-gfx</key>
				<string>onboard-1</string>
				<key>model</key>
				<string>Intel UHD Graphics 630 (Mobile)</string>
			</dict>
		</dict>

This will patch the Intel Card to the right ID for iGPU use with connectors and the single HDMI output we have on our mainboard. Audio should be working, too. 

(Optional): I had Problems during boot with the nvram ( Couldn't allocate runtime error. Therefore I changed from AptIOMemoryFix to the following drivers:

FwRuntimeServices.efi
OcQuirks.efi
MemoryAllocation.efi

This fixed the issue.

For me everything is working as expected: Handover, Sidecar also.

**Comment by quiggy** [comment]
Another enhancement: With the SSDT-PMC.aml from [this site](https://www.hackintosh-forum.de/forum/thread/46154-natives-nvram-auf-dem-z390-durchbruch/?pageNo=7) its also possible to use the native NVRAM without EmuVariableUefi.efi

**Comment by alexbohariuc** [comment]
@quiggy might try this. As far as I see you have a similar configuration (the only difference is that I have a Vega64 Nitro Plus)

**Comment by viktorstrate** [comment]
I couldn't get my iGPU to work, when "Internal graphics" was enabled in the BIOS the system wouldn't boot.

But I recently found this project that replaces EmuVariableUefi.efi. This solved my problems regarding booting with "Internal graphics" enabled.

https://github.com/ReddestDream/OcQuirks

After installing I changed two settings in the `OcQuirks.plist` (based on [this article](https://hackintosher.com/guides/get-z390-motherboards-working-hackintosh/))
- Changed __DevirtualiseMmio__ to __true__
- Changed __ForceExitBootServices__ to __false__

**Comment by nearlynogravitas** [comment]
Based on @cmer's OpenCore config in this repo, I have changed some fields so that the iGPU works.

Relevant branch: https://github.com/nearlynogravitas/gigabyte-z390-aorus-master-hackintosh/tree/igpu

Relevant commit: https://github.com/nearlynogravitas/gigabyte-z390-aorus-master-hackintosh/commit/e6311c73a90e28148fc2b9df10018d1c6ab65067

This allows for HDMI output from the iGPU for the i9-9900K, tested on the Aorus Pro Wifi.  I assume it would also work on the Aorus Master.

This was a useful reference: https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/ (Search for "Gigabyte Z390 AORUS Master and Coffee Lake CPU")

**Comment by cmer** [comment]
This is great thanks. I’m not going to merge this because my objective is to keep my build as close as possible to the iMac I am emulating, and it doesn’t support iGPU display. There might be some unknown stability issues related to doing this. Still, I think it’s awesome you were able to do it and that you have a commit for others to refer to, should they want to follow your lead.

**Comment by nearlynogravitas** [comment]
I agree that it should not be merged.  I just want to keep it in a branch somewhere for reference.  Maybe it's useful to someone.

The reason that I made it is that my RX 580 died.  I'm waiting on a replacement, so I am using the Intel 630 iGPU for now.  My hardware is nearly identical to yours, the only major difference being that I have the Wifi model rather than the Master model of the motherboard.
