### ISSUE TITLE
Ethernet Connection

### ISSUE THREAD

**Issue by Tom9876** [cmer/gigabyte-z390-aorus-master-hackintosh#78]
I use this repository successfully since quite a while. Thanks for making it available and regularly updating it.
With the last update to OpenCore 0.6.0 I have had problems with the Ethernet connection which stopped working. I use the standard Ethernet port from the Z390 AM. In the repository you (still) use the IntelMausiEthernet.kext. Looking in the documentation form OC 0.6.0 they seem to have moved to IntelMausi.kext. Using this kext (https://github.com/acidanthera/IntelMausi/releases) my Ethernet works again. 
I have seen in your hardware overview that you use a 10 GBit Ethernet card, therefore you not have noticed this issue.

**Comment by alexbohariuc** [comment]
Same here, had to change the kext.

**Comment by alexbohariuc** [comment]
Although with IntelMausi the ethernet works mine is stuck by default to 100Tx, not 1000T, which is a bummer since i have a Gigabit internet connection. If i change it manually to 1000T it gets disabled.

@cmer i know you use the aqc107, but could you check if everything is ok with the internal network card?

**Comment by cmer** [comment]
I actually started using the onboard NIC as well. I switched to `IntelMausi.kext` and it works like a charm.
