### ISSUE TITLE
BigSur

### ISSUE THREAD

**Issue by DejanOnTheGo** [cmer/gigabyte-z390-aorus-master-hackintosh#86]
Hey I also switched to Open Core 0.6.2.
Did you try to make BigSur (latest Beta) work on your configuration?

**Comment by cmer** [comment]
No I didn't try Big Sur yet.

**Comment by gajosr** [comment]
@DejanOnTheGo I have successfully upgraded from Catalina 10.15.7 (OC 0.6.3) to BigSure 11.0.1 today. Update directly form system preferences. I didn't make any changes to my OC configuration. Upgraded with no issues took about 30 minutes. BigSure works with no problems so far.

**Comment by Wizjonero** [comment]
I can confirm @gajosr, Big Sur works great under the current setup.

**Comment by helix0712** [comment]
Same here,
updated to BigSur 11.01 2 days ago with no issues using the current setup on Aorus Z390 i Pro Wifi. I started testing the Intel Bluetooth drivers before, which worked using Catalina, but for some reason my USBMap.kext did not seem to work anymore in BigSur. I created a new one and now am even able to use the onboard Intel Bluetooth and Wifi using drivers from https://github.com/OpenIntelWireless, which is great!

**Comment by Wizjonero** [comment]
@helix0712 this is VERY interesting! AFAIK Z390 has BT5.0, while my receiver is only BT4. Would be great if it worked out of the box!

**Comment by onastvar** [comment]
@helix0712 this is great, thanks! Could you share steps how to setup/install OpenIntelWireless drivers on BigSur w/OpenCore?

**Comment by cmer** [comment]
Any issues/bugs/hickups using the onboard BT+WIFI @helix0712? Tempted to give it a shot as well.

**Comment by helix0712** [comment]
Setup is quite easy. For Bluetooth grab the IntelBluetoothFirmware.kext and the IntelBluetoothInjector.kext from https://github.com/OpenIntelWireless/IntelBluetoothFirmware and put them in your KEXT Folder. After the reboot Bluetooth works for me without any flaws. 
I am testing AirportItlwm for the wireless part to leverage the facy feature like handoff and universal clipboard. Installation is as easy as for the Bluetooth: Grab the kext from https://github.com/OpenIntelWireless/itlwm/releases, put in your kext folder inside your efi and reboot. But the last Alpha i was trying failed with a Kernel Crash which seems to have been fixed by now, but still nature of Alpha code is instability :-) 

Regards,

Patrick

**Comment by lijie28** [comment]
@helix0712 
thanks for your information, it really helps!!!!
i just wanted to fix my sleep/wake issues caused by my bcm943602cs before.
But now i have fixed it by just using onboard in BT.
by the way, i'm using bigsur 11.1
